### ISSUE TITLE
Japanese subregion abreviations are ISO codes

### ISSUE THREAD

**Issue by jjb** [carmen-ruby/carmen#186] opened 2015-09-27 13:48 UTC
First of all, thank you for such a fantastic project, it's been of great value to me!

Looks like the abbreviations provided for Japanese subregions are ISO codes. Is this an issue of missing data, or are there not standard latin character abbreviations for Japanese subregions? (my initial research suggests this)

**Comment by CDainMiller** [comment] 2015-09-29 20:59
Thanks for this @jjb. I'll take a look at it later, I'm not immediately sure what the answer is but will get back to you.

**Comment by jjb** [comment] 2015-09-29 21:08
A bit more research suggests there are no established latin alpha abbreviations for Japanese subregions. In my own app I'm going to do something like:

```ruby
if subregion.code.to_i.to_s == subregion.code
  subregion.name
else
  subregion.code
end
```

So maybe it would be nice to be able to do `subregion.numeric_code_only?`

**Comment by swcraig** [comment] 2017-10-28 17:10
Hi @jjb, I know this is super old.

I don't quite understand what the problem is. Is your problem that the subregion codes for Japan are just numbers (represented as strings)?

**Comment by jjb** [comment] 2017-10-28 17:11
yes

**Comment by swcraig** [comment] 2017-10-28 17:21
I understand. In cases where the code is a string representation of a number, you would like to use the full name of the subregion - and otherwise use the code as normal (the two character string)?

If so, your suggested PR would be great. I would, however, prefer a name of `subregion.numeric_code?`. What do you think?

**Comment by jjb** [comment] 2017-10-28 17:24
sounds good. but first we should establish the answer to this:

> Is this an issue of missing data, or are there not standard latin character abbreviations for Japanese subregions?

**Comment by swcraig** [comment] 2017-10-28 17:32
This isn't an issue of missing data. The [ISO 3166-2 file](https://anonscm.debian.org/git/pkg-isocodes/iso-codes.git/plain/data/iso_3166-2.json) we retrieve our data from has them as integers (search for "JP" within that JSON). The [WIkipedia page for ISO 3166-2:JP](https://en.wikipedia.org/wiki/ISO_3166-2:JP#Current_codes) also corroborates with this. There are quite a few other countries that don't have textual representations for their subregion codes (such as [Czechia](https://en.wikipedia.org/wiki/ISO_3166-2:CZ) and [Barbados](https://en.wikipedia.org/wiki/ISO_3166-2:BB)).

**Comment by jjb** [comment] 2017-10-28 17:48
Gotcha. I figured, just wanted to make sure :)

good to know about the other countries, that makes this feature more valuable. I'll work on it right now

**Comment by jjb** [comment] 2017-10-28 18:25
@swcraig okay, PR is up! :)

**Comment by swcraig** [comment] 2017-11-04 19:13
Discussed and resolved in the associated PR.

**Closed by swcraig** 2017-11-04 19:13 UTC
